<?xml version="1.0"?>
<robot name="robotino" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.5" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="width_2" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height_2" value="0.1" /> <!-- Link 1 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
      ixx="1.0" ixy="0.0" ixz="0.0"
      iyy="1.0" iyz="0.0"
      izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint" type="prismatic">
    <parent link="base_link"/>
    <child link="cube_link"/>
    <origin xyz="0 ${width} ${height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="300" velocity="10.0" lower="-2" upper="2" />
  </joint>

  <link name="cube_link">
    <collision>
      <origin xyz="0 ${2*width} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width_2} ${width_2} ${height_2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${2*width} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width_2} ${width_2} ${height_2}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 ${2*width} 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
      ixx="1.0" ixy="0.0" ixz="0.0"
      iyy="1.0" iyz="0.0"
      izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="cube_link">        
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <mu1>0</mu1>
    <mu2>0</mu2>
    <fdir1>0 0 0</fdir1>
  </gazebo>

  <gazebo>    
    <plugin name="robotino_plugin" filename="librobotino_plugin.so"/>
  </gazebo>

</robot>