<?xml version="1.0"?>
<robot>
  <property name="M_SCALE" value="0.01"/>
  <property name="BASE_RADIUS" value="0.18"/>
  <property name="BASE_HEIGHT" value="0.03"/>
  <property name="BASE_MASS" value="0.001"/> <!-- 20 -->

  <property name="M_PI" value="3.1415926535897931"/>
  <property name="width" value="0.5" /> <!-- Square dimensions (widthxwidth) of beams -->
  <property name="height" value="0.5" /> <!-- Link 1 -->
  <property name="width_2" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <property name="height_2" value="0.5" /> <!-- Link 1 -->
  <property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->


  <property name="roll" value="${M_PI/2}" /> <!-- Space btw top of beam and the each joint -->
  <property name="yaw" value="${M_PI/2}" /> <!-- Space btw top of beam and the each joint -->
  
  <link name="world"/>

  <joint name="joint_x" type="prismatic">
    <parent link="world"/>
    <child link="int_link_xy"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10" velocity="10" lower="-100" upper="100" />
  </joint>

  <link name="int_link_xy">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1" ixy="0.0" ixz="0.0"
          iyy="1" iyz="0.0"
          izz="1" />
      </inertial>      
  </link>

  <joint name="joint_y" type="prismatic">
    <parent link="int_link_xy"/>
    <child link="int_link_yw"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="10" lower="-100" upper="100" />
  </joint>

   <link name="int_link_yw">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1" ixy="0.0" ixz="0.0"
          iyy="1" iyz="0.0"
          izz="1" />
      </inertial>
  </link>

  <joint name="revolute_w" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="int_link_yw"/>
    <child link="base_link"/>
    <axis xyz="0 0 1" />
  </joint>

  <macro name="robotino_body">
    
  	<link name="base_link">
      <inertial>
        <mass value="${BASE_MASS}" />
        <origin xyz="0 0 0.5" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>
      <visual>
        <origin xyz="0.01 0 0" rpy="0 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://robotino3_description/meshes/RobotinoBody.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
      <!-- <visual>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <geometry>
          <box size="0.1 0.05 0.02"/>
        </geometry>
      </visual> -->
      <collision>
        <origin xyz="0 0 ${BASE_HEIGHT/2+0.02}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${BASE_RADIUS}" length="${BASE_HEIGHT}"/>
        </geometry>
      </collision>
<!--       <collision>
        <origin xyz="0.01 0 0" rpy="0 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="package://robotino3_description/meshes/RobotinoBody.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </collision> -->
    </link>
    
    <wheel name="wheel1" parent="base_link">
      <origin xyz="0.065 0.11 0.04" rpy="0 0 ${M_PI/3}"/>
      <axis xyz="1 0 0"/>
    </wheel>
    <wheel name="wheel0" parent="base_link">
      <origin xyz="-0.13 0 0.04" rpy="0 0 0"/>
      <axis xyz="-1 0 0"/>
    </wheel>
    <wheel name="wheel2" parent="base_link">
      <origin xyz="0.065 -0.11 0.04" rpy="0 0 -${M_PI/3}"/>
      <axis xyz="1 0 0"/>
    </wheel>
    
    <command_bridge name="command_bridge" parent="base_link">
      <origin xyz="-0.05 0 0.13" rpy="0 0 ${M_PI/2}"/>
    </command_bridge>
    
    <camera name="camera" parent="base_link">
      <origin xyz="0.044 0 0.07" rpy="0 0 ${M_PI/2}"/>
    </camera>
    
<!--     <anglebracketusb name="anglebracketusb" parent="base_link">
      <origin xyz="0.008 0 0.137" rpy="0 0 ${M_PI/2}"/>
    </anglebracketusb> -->
    
<!--     <laser name="laser" parent="base_link">
      <origin xyz="-0.022 0 0.232" rpy="0 0 0"/>
    </laser> -->
    
    <laser name="laser" parent="base_link">
      <origin xyz="0.12 0 ${BASE_HEIGHT/2}" rpy="0 0 0"/>
    </laser>
  </macro>
</robot>
