<?xml version="1.0"?>
<robot name="test_cube" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <xacro:property name="M_PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.5" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="width_2" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height_2" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->


  <xacro:property name="roll" value="${M_PI/2}" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="yaw" value="${M_PI/2}" /> <!-- Space btw top of beam and the each joint -->



  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

<!--   <joint name="fixed2" type="fixed">
    <parent link="base_link"/>
    <child link="int_link_yw"/>
  </joint> -->

  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
      ixx="0" ixy="0.0" ixz="0.0"
      iyy="0" iyz="0.0"
      izz="0"/>
    </inertial>
  </link>

  <joint name="joint_x" type="prismatic">
    <parent link="base_link"/>
    <child link="int_link_xy"/>
    <origin xyz="0 ${width/2} ${height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="10" lower="0" upper="3" />
  </joint>

  <link name="int_link_xy">
    <collision>
      <origin xyz="0 0.05 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0.05 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0.05 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
      ixx="1" ixy="0.0" ixz="0.0"
      iyy="1" iyz="0.0"
      izz="1"/>
    </inertial>
  </link>

  <joint name="joint_y" type="prismatic">
    <parent link="int_link_xy"/>
    <child link="int_link_yw"/>
    <origin xyz="0.05 0.05 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10" velocity="10" lower="0" upper="3" />
  </joint>

  <link name="int_link_yw">
    <collision>
      <origin xyz="0.05 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.05 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0.05 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
      ixx="1" ixy="0.0" ixz="0.0"
      iyy="1" iyz="0.0"
      izz="1"/>
    </inertial>
  </link>

  <joint name="revolute_w" type="continuous">
    <parent link="int_link_yw"/>
    <child link="wheel"/>
    <origin xyz="0.1 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name="wheel">
    <collision>
      <origin xyz="0.05 0 0" rpy="${roll} 0 ${yaw}"/>
      <geometry>
        <cylinder radius="${height_2/2}" length="${width_2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.05 0 0" rpy="${roll} 0 ${yaw}"/>
      <geometry>
        <cylinder radius="${height_2/2}" length="${width_2}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0.05 0 0" rpy="${roll} 0 ${yaw}"/>
      <mass value="1"/>
      <inertia
      ixx="1" ixy="0.0" ixz="0.0"
      iyy="1" iyz="0.0"
      izz="1"/>
    </inertial>
  </link>

  <gazebo reference="wheel">        
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <mu1>0</mu1>
    <mu2>0</mu2>
    <fdir1>1 0 0</fdir1>
  </gazebo>

  <gazebo>    
    <plugin name="robotino_plugin" filename="librobotino_plugin.so"/>
  </gazebo>

</robot>